<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_theme_suggestions_page_alter().
 */
function segura_viudas_citas_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'segura_viudas_citas.citas_form') {
    $suggestions[] = 'page__citas_form';
  }
}

/**
 * Implements hook_theme().
 */
function segura_viudas_citas_theme($existing, $type, $theme, $path) {
  return [
    'citas_form' => [
      'variables' => ['form' => NULL],
      'template' => 'citas-form',
      'path' => $path . '/templates',
      'libraries' => [
        'segura_viudas_citas/segura_viudas_citas',
      ],
    ],
    'citas_admin_page' => [
      'template' => 'citas-admin',
      'path' => $path . '/templates',
    ],
    'gestion_citas' => [
      'variables' => ['title' => NULL, 'rows' => []],
      'template' => 'gestion-citas',
    ],
    'node__citas' => [
      'base hook' => 'node',
      'template' => 'node--citas',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_entity_view().
 */
function segura_viudas_citas_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'citas' && $view_mode === 'full') {
    $url = \Drupal\Core\Url::fromRoute('segura_viudas_citas.admin_citas', ['node' => $entity->id()]);
    $response = new \Symfony\Component\HttpFoundation\RedirectResponse($url->toString());
    $response->send();
    exit;
  }
}
